name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "^1.7.0"
        terraform_wrapper: false

    - name: Run unit tests
      run: make test

    - name: Run acceptance tests
      run: |
        make docker-start
        sh -c 'TESTARGS=-count=1 ./wait-for localhost:1433 -- make testacc-local'
        make docker-stop
